# Generated by Django 2.0.2 on 2023-04-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_missing', models.DateField(default=0)),
                ('sfirst_name', models.CharField(max_length=30)),
                ('slast_name', models.CharField(max_length=30)),
                ('age_at_missing', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
            ],
        ),
    ]
