# Generated by Django 4.2 on 2023-04-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingpersonsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missing',
            old_name='sfirst_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='missing',
            old_name='slast_name',
            new_name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='missing',
            name='date_missing',
        ),
        migrations.AddField(
            model_name='missing',
            name='case_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missing',
            name='age_at_missing',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='missing',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='missing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='missing',
            name='race',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='missing',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='missing',
            name='Date_Missing',
            field=models.DateField(default=None),
        ),
    ]
